#target aftereffects
#targetengine "SRTRollingLyricsImporter"

/*
 * 滚动字幕生成器 2.0.0 测试版
 * 可停靠面板；无需第三方插件。
 */
(function SRTRollingLyricsImporter(thisObj) {
    var APP_NAME = "滚动字幕生成器";
    var VERSION = "2.0.0-beta";
    var CONFIG_SECTION = "SRTRollingLyricsImporter.DefaultConfig";
    var CONFIG_VERSION = "2";
    var AUTO = "AUTO_";
    var state = { srtFile: null, entries: [], ui: {}, factoryConfig: null, fontCache: null };
    var TEXT_KEYS = ["fontName","fontSize","fontColor","strokeWidth","strokeColor","lineSpacing","centerX","centerY","scrollDuration","currentOpacity","neighborOpacity","currentScale","neighborScale","visibleNeighbors","shadowColor","shadowOpacity","shadowDirection","shadowDistance","shadowSoftness","backgroundColor","backgroundOpacity","paddingX","paddingY","roundness","borderColor","borderOpacity","borderWidth","borderGlowIntensity","borderGlowRadius","textGlowIntensity","textGlowRadius"];
    var CHECK_KEYS = ["extendComp","shadowEnabled","backgroundEnabled","textGlowEnabled","borderGlowEnabled"];

    function trim(value) { return String(value === undefined || value === null ? "" : value).replace(/^\s+|\s+$/g, ""); }
    function clamp(value, low, high) { return Math.max(low, Math.min(high, value)); }
    function numberValue(text, fallback, low, high) { var value = parseFloat(text); if (isNaN(value)) { value = fallback; } return clamp(value, low, high); }
    function intValue(text, fallback, low, high) { return Math.round(numberValue(text, fallback, low, high)); }
    function pad(value, length) { var text = String(value); while (text.length < length) { text = "0" + text; } return text; }
    function parseColor(text, fallback) { var value = trim(text).replace(/^#/, ""); if (/^[0-9a-fA-F]{3}$/.test(value)) { value = value.charAt(0)+value.charAt(0)+value.charAt(1)+value.charAt(1)+value.charAt(2)+value.charAt(2); } if (!/^[0-9a-fA-F]{6}$/.test(value)) { return fallback; } return [parseInt(value.substr(0,2),16)/255,parseInt(value.substr(2,2),16)/255,parseInt(value.substr(4,2),16)/255]; }
    function fail(message) { alert(APP_NAME + "\r\r" + message, APP_NAME); }
    function escapeExpressionString(value) { return String(value).replace(/\\/g, "\\\\").replace(/\"/g, "\\\""); }
    function uniqueLayerName(comp, baseName) { var name = baseName, suffix = 2; while (comp.layer(name) !== null) { name = baseName + " " + suffix; suffix++; } return name; }
    function readTextFile(file) { if (!file || !file.exists) { throw new Error("字幕文件不存在。"); } file.encoding = "UTF-8"; if (!file.open("r")) { throw new Error("无法读取字幕文件。"); } var text = file.read(); file.close(); return text.replace(/^\uFEFF/, ""); }
    function parseTime(h, m, s, ms) { return Number(h) * 3600 + Number(m) * 60 + Number(s) + Number(ms) / 1000; }
    function parseSRT(raw) {
        raw = raw.replace(/^\uFEFF/, "").replace(/\r\n/g, "\n").replace(/\r/g, "\n");
        var blocks = raw.split(/\n\s*\n/), entries = [], pattern = /^(\d{1,2}):(\d{2}):(\d{2})[,.](\d{3})\s*-->\s*(\d{1,2}):(\d{2}):(\d{2})[,.](\d{3})/, i, j, k, lines, match, timeLine, textLines, start, end;
        for (i = 0; i < blocks.length; i++) {
            lines = blocks[i].split("\n"); match = null; timeLine = -1;
            for (j = 0; j < lines.length; j++) { match = trim(lines[j]).match(pattern); if (match) { timeLine = j; break; } }
            if (!match) { continue; }
            textLines = []; for (k = timeLine + 1; k < lines.length; k++) { if (trim(lines[k])) { textLines.push(lines[k].replace(/\\N/g, "\r")); } }
            start = parseTime(match[1],match[2],match[3],match[4]); end = parseTime(match[5],match[6],match[7],match[8]);
            if (textLines.length && end > start) { entries.push({start:start,end:end,text:textLines.join("\r")}); }
        }
        entries.sort(function (a,b) { return a.start - b.start; }); return entries;
    }

    function chooseColor(edit) { if (!$.colorPicker) { fail("当前 AE 不支持系统选色器，请直接输入 #RRGGBB。"); return; } var initial = parseInt(trim(edit.text).replace(/^#/, ""), 16); if (isNaN(initial)) { initial = 0xFFFFFF; } var picked = $.colorPicker(initial); if (picked >= 0) { edit.text = "#" + pad(picked.toString(16).toUpperCase(), 6).substr(-6); } }
    function availableFonts() { if (state.fontCache) { return state.fontCache; } state.fontCache = []; try { var groups = app.fonts.allFonts, i, j, f; for (i=0;i<groups.length;i++) { for (j=0;j<groups[i].length;j++) { f=groups[i][j]; if (f.postScriptName) { state.fontCache.push({label:(f.nativeFullName||f.fullName||f.postScriptName)+"  ["+f.postScriptName+"]",postScriptName:f.postScriptName}); } } } } catch (ignore) {} return state.fontCache; }
    function chooseFont(edit) { var fonts=availableFonts(); if (!fonts.length) { fail("字体列表需要 AE 24.6 或更高版本；当前仍可手动输入 PostScript 字体名。"); return; } var dlg=new Window("dialog","选择字体"), search=dlg.add("edittext",undefined,""), list=dlg.add("listbox",undefined,[]), buttons=dlg.add("group"), ok=buttons.add("button",undefined,"确定",{name:"ok"}), i; dlg.orientation="column";dlg.alignChildren=["fill","top"];dlg.preferredSize=[620,600];list.preferredSize=[600,460];buttons.alignment="right";buttons.add("button",undefined,"取消",{name:"cancel"}); function refresh(){var q=trim(search.text).toLowerCase(),item;list.removeAll();for(i=0;i<fonts.length;i++){if(!q||fonts[i].label.toLowerCase().indexOf(q)>=0){item=list.add("item",fonts[i].label);item.fontPS=fonts[i].postScriptName;}}} search.onChanging=refresh;list.onDoubleClick=function(){if(list.selection){dlg.close(1);}};refresh();search.active=true;if(dlg.show()===1&&list.selection){edit.text=list.selection.fontPS;} }

    function snapshotUI() { var out={},u=state.ui,i,key; for(i=0;i<TEXT_KEYS.length;i++){key=TEXT_KEYS[i];out[key]=String(u[key].text);} for(i=0;i<CHECK_KEYS.length;i++){key=CHECK_KEYS[i];out[key]=u[key].value?"1":"0";} return out; }
    function applyUI(config) { var u=state.ui,i,key; for(i=0;i<TEXT_KEYS.length;i++){key=TEXT_KEYS[i];if(config[key]!==undefined){u[key].text=config[key];}} for(i=0;i<CHECK_KEYS.length;i++){key=CHECK_KEYS[i];if(config[key]!==undefined){u[key].value=config[key]==="1";}} }
    function saveDefaults() { var config=snapshotUI(),i,key; try { for(i=0;i<TEXT_KEYS.length;i++){key=TEXT_KEYS[i];app.settings.saveSetting(CONFIG_SECTION,key,encodeURIComponent(config[key]));} for(i=0;i<CHECK_KEYS.length;i++){key=CHECK_KEYS[i];app.settings.saveSetting(CONFIG_SECTION,key,config[key]);} app.settings.saveSetting(CONFIG_SECTION,"version",CONFIG_VERSION);app.settings.saveSetting(CONFIG_SECTION,"saved","1");alert("当前样式已保存为默认值。",APP_NAME); } catch(error){fail("保存默认配置失败：\r"+error.toString());} }
    function loadDefaults() { if(!app.settings.haveSetting(CONFIG_SECTION,"saved")||app.settings.getSetting(CONFIG_SECTION,"saved")!=="1"){return;} var config={},i,key;try{for(i=0;i<TEXT_KEYS.length;i++){key=TEXT_KEYS[i];if(app.settings.haveSetting(CONFIG_SECTION,key)){config[key]=decodeURIComponent(app.settings.getSetting(CONFIG_SECTION,key));}}for(i=0;i<CHECK_KEYS.length;i++){key=CHECK_KEYS[i];if(app.settings.haveSetting(CONFIG_SECTION,key)){config[key]=app.settings.getSetting(CONFIG_SECTION,key);}}applyUI(config);}catch(error){fail("读取默认配置失败：\r"+error.toString());} }
    function restoreFactory() { applyUI(state.factoryConfig); try{app.settings.saveSetting(CONFIG_SECTION,"saved","0");}catch(ignore){} alert("已恢复出厂默认配置。",APP_NAME); }
    function settingsFromUI() { var u=state.ui; return {fontName:trim(u.fontName.text),fontSize:numberValue(u.fontSize.text,42,4,500),fontColor:parseColor(u.fontColor.text,[1,1,1]),strokeWidth:numberValue(u.strokeWidth.text,0,0,50),strokeColor:parseColor(u.strokeColor.text,[0,0,0]),lineSpacing:numberValue(u.lineSpacing.text,150,1,4000),centerX:numberValue(u.centerX.text,960,-30000,30000),centerY:numberValue(u.centerY.text,540,-30000,30000),scrollDuration:numberValue(u.scrollDuration.text,0.3,0,20),currentOpacity:numberValue(u.currentOpacity.text,100,0,100),neighborOpacity:numberValue(u.neighborOpacity.text,32,0,100),currentScale:numberValue(u.currentScale.text,112,0,1000),neighborScale:numberValue(u.neighborScale.text,94,0,1000),visibleNeighbors:intValue(u.visibleNeighbors.text,1,0,20),extendComp:u.extendComp.value,shadowEnabled:u.shadowEnabled.value,shadowColor:parseColor(u.shadowColor.text,[0,0,0]),shadowOpacity:numberValue(u.shadowOpacity.text,55,0,100),shadowDirection:numberValue(u.shadowDirection.text,135,-360,360),shadowDistance:numberValue(u.shadowDistance.text,4,0,1000),shadowSoftness:numberValue(u.shadowSoftness.text,10,0,1000),backgroundEnabled:u.backgroundEnabled.value,backgroundColor:parseColor(u.backgroundColor.text,[0.08,0.16,0.28]),backgroundOpacity:numberValue(u.backgroundOpacity.text,72,0,100),paddingX:numberValue(u.paddingX.text,90,0,4000),paddingY:numberValue(u.paddingY.text,42,0,4000),roundness:numberValue(u.roundness.text,26,0,1000),borderColor:parseColor(u.borderColor.text,[0.36,0.72,1]),borderOpacity:numberValue(u.borderOpacity.text,75,0,100),borderWidth:numberValue(u.borderWidth.text,2.2,0,100),borderGlowEnabled:u.borderGlowEnabled.value,borderGlowIntensity:numberValue(u.borderGlowIntensity.text,0.75,0,100),borderGlowRadius:numberValue(u.borderGlowRadius.text,18,0,1000),textGlowEnabled:u.textGlowEnabled.value,textGlowIntensity:numberValue(u.textGlowIntensity.text,1.15,0,100),textGlowRadius:numberValue(u.textGlowRadius.text,24,0,1000)}; }

    function addSlider(effects,name,value){var fx=effects.addProperty("ADBE Slider Control");fx.name=name;fx.property(1).setValue(value);}
    function addPoint(effects,name,value){var fx=effects.addProperty("ADBE Point Control");fx.name=name;fx.property(1).setValue(value);}
    function addColor(effects,name,value){var fx=effects.addProperty("ADBE Color Control");fx.name=name;fx.property(1).setValue(value);}
    function setEase(property){var i,ease;try{ease=new KeyframeEase(0,75);for(i=1;i<=property.numKeys;i++){property.setTemporalEaseAtKey(i,[ease],[ease]);property.setInterpolationTypeAtKey(i,KeyframeInterpolationType.BEZIER,KeyframeInterpolationType.BEZIER);}}catch(ignore){}}
    function setHold(property){var i;try{for(i=1;i<=property.numKeys;i++){property.setInterpolationTypeAtKey(i,KeyframeInterpolationType.HOLD,KeyframeInterpolationType.HOLD);}}catch(ignore){}}
    function addShadow(layer,ctrlName,s){if(!s.shadowEnabled){return;}try{var fx=layer.property("ADBE Effect Parade").addProperty("ADBE Drop Shadow");fx.name=AUTO+"Lyric Shadow";fx.property(1).expression='thisComp.layer("'+ctrlName+'").effect("Shadow Color")(1);';fx.property(2).expression='thisComp.layer("'+ctrlName+'").effect("Shadow Opacity")(1);';fx.property(3).expression='thisComp.layer("'+ctrlName+'").effect("Shadow Direction")(1);';fx.property(4).expression='thisComp.layer("'+ctrlName+'").effect("Shadow Distance")(1);';fx.property(5).expression='thisComp.layer("'+ctrlName+'").effect("Shadow Softness")(1);';}catch(ignore){}}
    function addGlow(layer,ctrlName,radiusName,intensityName,activeExpression){try{var fx=layer.property("ADBE Effect Parade").addProperty("ADBE Glo2");fx.name=AUTO+"Glow";fx.property(3).expression='thisComp.layer("'+ctrlName+'").effect("'+radiusName+'")(1);';fx.property(4).expression=activeExpression||'thisComp.layer("'+ctrlName+'").effect("'+intensityName+'")(1);';}catch(ignore){}}

    function generate() {
        var comp=app.project.activeItem;if(!(comp instanceof CompItem)){fail("请先打开并选中目标合成。");return;}if(!state.srtFile||!state.srtFile.exists){fail("请先在“项目”页选择 UTF-8 SRT 文件。");return;}
        var entries;try{entries=parseSRT(readTextFile(state.srtFile));}catch(readError){fail(readError.toString());return;}if(!entries.length){fail("没有找到有效字幕，请检查 SRT 时间轴与 UTF-8 编码。");return;}
        var s=settingsFromUI(),lastEnd=entries[entries.length-1].end,originalTop=comp.numLayers?comp.layer(1):null,backgrounds=[],i,n,entry,layer,doc,textProp,rect,opacity,scale,bg,root,group,contents,shape,fill,stroke,textName,transitionStart;
        app.beginUndoGroup("生成 SRT 滚动歌词");
        try{
            if(s.extendComp&&comp.duration<lastEnd+0.5){comp.duration=lastEnd+0.5;}
            var ctrlName=uniqueLayerName(comp,AUTO+"SCROLL_CONTROLS"),ctrl=comp.layers.addNull(comp.duration);ctrl.name=ctrlName;ctrl.label=9;ctrl.comment="滚动歌词统一控制层；除滚动时长外，视觉参数均可在生成后修改。";
            var effects=ctrl.property("ADBE Effect Parade");
            addSlider(effects,"Scroll Index",1);addSlider(effects,"Current Lyric",0);addSlider(effects,"Line Spacing",s.lineSpacing);addPoint(effects,"Lyrics Center",[s.centerX,s.centerY]);addSlider(effects,"Font Size",s.fontSize);addColor(effects,"Font Color",s.fontColor);addSlider(effects,"Stroke Width",s.strokeWidth);addColor(effects,"Stroke Color",s.strokeColor);addSlider(effects,"Current Opacity",s.currentOpacity);addSlider(effects,"Neighbor Opacity",s.neighborOpacity);addSlider(effects,"Visible Neighbors",s.visibleNeighbors);addSlider(effects,"Current Scale",s.currentScale);addSlider(effects,"Neighbor Scale",s.neighborScale);addSlider(effects,"Master Opacity",100);addSlider(effects,"Master Scale",100);addSlider(effects,"Background Enabled",s.backgroundEnabled?100:0);addColor(effects,"Background Color",s.backgroundColor);addSlider(effects,"Background Opacity",s.backgroundOpacity);addSlider(effects,"Background Padding X",s.paddingX);addSlider(effects,"Background Padding Y",s.paddingY);addSlider(effects,"Corner Roundness",s.roundness);addColor(effects,"Border Color",s.borderColor);addSlider(effects,"Border Opacity",s.borderOpacity);addSlider(effects,"Border Width",s.borderWidth);addSlider(effects,"Border Glow Intensity",s.borderGlowEnabled?s.borderGlowIntensity:0);addSlider(effects,"Border Glow Radius",s.borderGlowRadius);addSlider(effects,"Text Glow Intensity",s.textGlowEnabled?s.textGlowIntensity:0);addSlider(effects,"Text Glow Radius",s.textGlowRadius);addColor(effects,"Shadow Color",s.shadowColor);addSlider(effects,"Shadow Opacity",s.shadowEnabled?s.shadowOpacity:0);addSlider(effects,"Shadow Direction",s.shadowDirection);addSlider(effects,"Shadow Distance",s.shadowDistance);addSlider(effects,"Shadow Softness",s.shadowSoftness);
            var scroll=effects.property("Scroll Index").property(1),current=effects.property("Current Lyric").property(1);scroll.setValueAtTime(0,1);current.setValueAtTime(0,entries[0].start<=0?1:0);if(entries[0].start>0){scroll.setValueAtTime(entries[0].start,1);current.setValueAtTime(entries[0].start,1);}for(i=1;i<entries.length;i++){transitionStart=Math.max(entries[i-1].start,entries[i].start-s.scrollDuration);scroll.setValueAtTime(transitionStart,i);scroll.setValueAtTime(entries[i].start,i+1);current.setValueAtTime(entries[i].start,i+1);}current.setValueAtTime(lastEnd,0);setEase(scroll);setHold(current);
            ctrl.property("ADBE Transform Group").property("ADBE Position").expression='var c=effect("Scroll Index")(1),gap=effect("Line Spacing")(1),p=effect("Lyrics Center")(1);[p[0]-thisComp.width/2,p[1]-(c-1)*gap];';
            var fontName=uniqueLayerName(comp,AUTO+"FONT_STYLE"),fontLayer=comp.layers.addText("Font Style Template");fontLayer.name=fontName;fontLayer.label=14;fontLayer.comment="在字符面板修改此层字体，全部滚动歌词会同步。";fontLayer.enabled=false;fontLayer.guideLayer=true;textProp=fontLayer.property("ADBE Text Properties").property("ADBE Text Document");doc=textProp.value;doc.fontSize=s.fontSize;if(s.fontName){try{doc.font=s.fontName;}catch(ignoreFont){}}textProp.setValue(doc);
            for(n=0;n<entries.length;n++){
                entry=entries[n];layer=comp.layers.addText(entry.text);layer.name=AUTO+"SRT_"+pad(n+1,3)+"  "+entry.text.replace(/\r|\n/g," / ").substr(0,36);layer.label=10;layer.inPoint=0;layer.outPoint=comp.duration;textProp=layer.property("ADBE Text Properties").property("ADBE Text Document");doc=textProp.value;doc.fontSize=s.fontSize;doc.applyFill=true;doc.fillColor=s.fontColor;doc.applyStroke=s.strokeWidth>0;doc.strokeColor=s.strokeColor;doc.strokeWidth=s.strokeWidth;doc.justification=ParagraphJustification.CENTER_JUSTIFY;doc.autoLeading=true;if(s.fontName){try{doc.font=s.fontName;}catch(ignoreLayerFont){}}textProp.setValue(doc);textProp.expression='var c=thisComp.layer("'+ctrlName+'"),f=thisComp.layer("'+fontName+'").text.sourceText.style.font,sw=c.effect("Stroke Width")(1);text.sourceText.style.setFont(f).setFontSize(c.effect("Font Size")(1)).setFillColor(c.effect("Font Color")(1)).setApplyStroke(sw>0).setStrokeWidth(sw).setStrokeColor(c.effect("Stroke Color")(1));';rect=layer.sourceRectAtTime(0,false);layer.property("ADBE Transform Group").property("ADBE Anchor Point").setValue([rect.left+rect.width/2,rect.top+rect.height/2]);layer.property("ADBE Transform Group").property("ADBE Position").setValue([comp.width/2,n*s.lineSpacing]);layer.setParentWithJump(ctrl);
                opacity=layer.property("ADBE Transform Group").property("ADBE Opacity");opacity.expression='var c=thisComp.layer("'+ctrlName+'"),a=Math.round(c.effect("Current Lyric")(1)),d=Math.abs(a-'+String(n+1)+'),v=Math.round(c.effect("Visible Neighbors")(1)),o=a<1?0:(d===0?c.effect("Current Opacity")(1):(d<=v?c.effect("Neighbor Opacity")(1):0));o*c.effect("Master Opacity")(1)/100;';scale=layer.property("ADBE Transform Group").property("ADBE Scale");scale.expression='var c=thisComp.layer("'+ctrlName+'"),a=Math.round(c.effect("Current Lyric")(1)),s=a==='+String(n+1)+'?c.effect("Current Scale")(1):c.effect("Neighbor Scale")(1);[s,s]*c.effect("Master Scale")(1)/100;';addShadow(layer,ctrlName,s);if(s.textGlowEnabled){addGlow(layer,ctrlName,"Text Glow Radius","Text Glow Intensity",'var c=thisComp.layer("'+ctrlName+'"),a=Math.round(c.effect("Current Lyric")(1));a==='+String(n+1)+'?c.effect("Text Glow Intensity")(1):0;');}
                if(s.backgroundEnabled){bg=comp.layers.addShape();bg.name=AUTO+"SRT_BG_"+pad(n+1,3);bg.label=11;bg.inPoint=0;bg.outPoint=comp.duration;root=bg.property("ADBE Root Vectors Group");group=root.addProperty("ADBE Vector Group");group.name="Active Lyric Background";contents=group.property("ADBE Vectors Group");shape=contents.addProperty("ADBE Vector Shape - Rect");textName=escapeExpressionString(layer.name);shape.property("ADBE Vector Rect Size").expression='var c=thisComp.layer("'+ctrlName+'"),r=thisComp.layer("'+textName+'").sourceRectAtTime(time,false),s=c.effect("Current Scale")(1)/100;[r.width*s+c.effect("Background Padding X")(1),r.height*s+c.effect("Background Padding Y")(1)];';shape.property("ADBE Vector Rect Roundness").expression='thisComp.layer("'+ctrlName+'").effect("Corner Roundness")(1);';fill=contents.addProperty("ADBE Vector Graphic - Fill");fill.property("ADBE Vector Fill Color").expression='thisComp.layer("'+ctrlName+'").effect("Background Color")(1);';stroke=contents.addProperty("ADBE Vector Graphic - Stroke");stroke.property("ADBE Vector Stroke Color").expression='thisComp.layer("'+ctrlName+'").effect("Border Color")(1);';stroke.property("ADBE Vector Stroke Opacity").expression='thisComp.layer("'+ctrlName+'").effect("Border Opacity")(1);';stroke.property("ADBE Vector Stroke Width").expression='thisComp.layer("'+ctrlName+'").effect("Border Width")(1);';bg.property("ADBE Transform Group").property("ADBE Position").expression='thisComp.layer("'+ctrlName+'").effect("Lyrics Center")(1);';bg.property("ADBE Transform Group").property("ADBE Opacity").expression='var c=thisComp.layer("'+ctrlName+'"),a=Math.round(c.effect("Current Lyric")(1));(a==='+String(n+1)+'?c.effect("Background Enabled")(1)*c.effect("Background Opacity")(1)/100:0)*c.effect("Master Opacity")(1)/100;';if(s.borderGlowEnabled){addGlow(bg,ctrlName,"Border Glow Radius","Border Glow Intensity",null);}backgrounds.push(bg);}
            }
            for(i=0;i<backgrounds.length;i++){if(originalTop){backgrounds[i].moveBefore(originalTop);}else{backgrounds[i].moveToEnd();}}ctrl.moveToBeginning();fontLayer.moveAfter(ctrl);comp.time=entries[0].start;alert("生成完成！\r\r字幕数量："+entries.length+"\r统一控制层："+ctrlName+"\r字体样式层："+fontName+"\r\r视觉参数可在控制层继续修改；滚动时长需在面板中调整后重新生成。",APP_NAME);
        }catch(error){fail("生成过程中发生错误：\r"+error.toString()+"\r行号："+(error.line||"未知"));}finally{app.endUndoGroup();}
    }

    function addEdit(parent,label,value,chars){var group=parent.add("group"),caption=group.add("statictext",undefined,label),edit=group.add("edittext",undefined,String(value));caption.preferredSize.width=92;edit.characters=chars||8;return edit;}
    function addInline(parent,label,value,chars){parent.add("statictext",undefined,label);var edit=parent.add("edittext",undefined,String(value));edit.characters=chars||6;return edit;}
    function addColorRow(parent,label,value,key){var group=parent.add("group");group.add("statictext",undefined,label).preferredSize.width=92;state.ui[key]=group.add("edittext",undefined,value);state.ui[key].characters=9;var button=group.add("button",undefined,"选色");button.onClick=function(){chooseColor(state.ui[key]);};}
    function buildUI(owner){var win=owner instanceof Panel?owner:new Window("palette",APP_NAME+" "+VERSION,undefined,{resizeable:true});win.orientation="column";win.alignChildren=["fill","top"];win.preferredSize=[760,560];var tabs=win.add("tabbedpanel"),project=tabs.add("tab",undefined,"项目"),lyrics=tabs.add("tab",undefined,"歌词"),motion=tabs.add("tab",undefined,"布局/动画"),style=tabs.add("tab",undefined,"背景/效果"),all=[project,lyrics,motion,style],i,u=state.ui;tabs.alignChildren=["fill","fill"];tabs.preferredSize=[740,470];for(i=0;i<all.length;i++){all[i].orientation="column";all[i].alignChildren=["fill","top"];}
        var files=project.add("panel",undefined,"输入与目标");files.orientation="column";files.alignChildren=["fill","center"];var fileRow=files.add("group");fileRow.add("statictext",undefined,"SRT 字幕").preferredSize.width=92;u.srtPath=fileRow.add("edittext",undefined,"");u.srtPath.characters=48;u.srtPath.enabled=false;var browse=fileRow.add("button",undefined,"选择");browse.onClick=function(){var file=File.openDialog("选择 UTF-8 SRT 字幕","SRT 字幕:*.srt");if(file){try{state.entries=parseSRT(readTextFile(file));if(!state.entries.length){throw new Error("没有有效字幕。");}state.srtFile=file;u.srtPath.text=file.fsName;u.summary.text="已读取 "+state.entries.length+" 条，时间范围 "+state.entries[0].start.toFixed(2)+"–"+state.entries[state.entries.length-1].end.toFixed(2)+" 秒";}catch(error){state.srtFile=null;state.entries=[];u.srtPath.text="";fail(error.toString());}}};u.summary=files.add("statictext",undefined,"尚未选择字幕。生成时使用当前选中的 AE 合成。");u.extendComp=files.add("checkbox",undefined,"字幕超出时自动延长合成");u.extendComp.value=true;project.add("statictext",undefined,"流程：打开目标合成 → 选择 SRT → 调整分页参数 → 点击“生成到当前合成”。\rSRT 每个字幕块可包含多行，适合双语歌词。",{multiline:true}).preferredSize.width=700;
        var lyricPanel=lyrics.add("panel",undefined,"字体与文字");lyricPanel.orientation="column";lyricPanel.alignChildren=["left","center"];var fontRow=lyricPanel.add("group");fontRow.add("statictext",undefined,"字体").preferredSize.width=92;u.fontName=fontRow.add("edittext",undefined,"");u.fontName.characters=30;var fontButton=fontRow.add("button",undefined,"选择字体");fontButton.onClick=function(){chooseFont(u.fontName);};var sizeRow=lyricPanel.add("group");sizeRow.add("statictext",undefined,"字号").preferredSize.width=92;u.fontSize=addInline(sizeRow,"","42",6);u.strokeWidth=addInline(sizeRow,"描边宽度","0",6);addColorRow(lyricPanel,"文字颜色","#FFFFFF","fontColor");addColorRow(lyricPanel,"描边颜色","#000000","strokeColor");lyricPanel.add("statictext",undefined,"字体在生成后可通过 AUTO_FONT_STYLE 与字符面板统一替换。",{multiline:true});
        var layout=motion.add("panel",undefined,"位置与滚动");layout.orientation="column";layout.alignChildren=["left","center"];var pos=layout.add("group");u.centerX=addInline(pos,"中心 X","960",7);u.centerY=addInline(pos,"中心 Y","540",7);u.lineSpacing=addInline(pos,"行距","150",7);var timing=layout.add("group");u.scrollDuration=addInline(timing,"滚动秒","0.30",6);u.visibleNeighbors=addInline(timing,"显示相邻句数","1",4);var opacityRow=layout.add("group");u.currentOpacity=addInline(opacityRow,"当前透明度","100",5);u.neighborOpacity=addInline(opacityRow,"相邻透明度","32",5);var scaleRow=layout.add("group");u.currentScale=addInline(scaleRow,"当前缩放 %","112",5);u.neighborScale=addInline(scaleRow,"相邻缩放 %","94",5);layout.add("statictext",undefined,"滚动秒决定生成的关键帧提前量；更改它需要重新生成。其余项目可在生成后的控制层修改。",{multiline:true}).preferredSize.width=700;
        var shadow=style.add("panel",undefined,"文字阴影与发光");shadow.orientation="column";shadow.alignChildren=["left","center"];var shadowSwitch=shadow.add("group");u.shadowEnabled=shadowSwitch.add("checkbox",undefined,"启用阴影");u.shadowEnabled.value=true;u.textGlowEnabled=shadowSwitch.add("checkbox",undefined,"当前句发光");u.textGlowEnabled.value=true;u.textGlowIntensity=addInline(shadowSwitch,"强度","1.15",5);u.textGlowRadius=addInline(shadowSwitch,"范围","24",5);addColorRow(shadow,"阴影颜色","#000000","shadowColor");var shadowValues=shadow.add("group");u.shadowOpacity=addInline(shadowValues,"透明度","55",4);u.shadowDirection=addInline(shadowValues,"方向","135",4);u.shadowDistance=addInline(shadowValues,"距离","4",4);u.shadowSoftness=addInline(shadowValues,"柔和度","10",4);
        var background=style.add("panel",undefined,"当前句背景与边框");background.orientation="column";background.alignChildren=["left","center"];var bgSwitch=background.add("group");u.backgroundEnabled=bgSwitch.add("checkbox",undefined,"启用圆角背景");u.backgroundEnabled.value=true;u.borderGlowEnabled=bgSwitch.add("checkbox",undefined,"边框发光");u.borderGlowEnabled.value=true;addColorRow(background,"背景颜色","#142947","backgroundColor");var bgValues=background.add("group");u.backgroundOpacity=addInline(bgValues,"透明度","72",4);u.paddingX=addInline(bgValues,"水平留白","90",5);u.paddingY=addInline(bgValues,"垂直留白","42",5);u.roundness=addInline(bgValues,"圆角","26",5);addColorRow(background,"边框颜色","#5CB8FF","borderColor");var borderValues=background.add("group");u.borderOpacity=addInline(borderValues,"透明度","75",4);u.borderWidth=addInline(borderValues,"宽度","2.2",5);u.borderGlowIntensity=addInline(borderValues,"发光强度","0.75",5);u.borderGlowRadius=addInline(borderValues,"范围","18",5);
        var actions=win.add("group");actions.alignment=["fill","bottom"];var save=actions.add("button",undefined,"保存当前为默认"),factory=actions.add("button",undefined,"恢复出厂默认"),generateButton=actions.add("button",undefined,"生成到当前合成");generateButton.alignment=["fill","center"];generateButton.preferredSize.height=38;save.onClick=saveDefaults;factory.onClick=restoreFactory;generateButton.onClick=generate;state.factoryConfig=snapshotUI();loadDefaults();tabs.selection=0;win.onResizing=win.onResize=function(){this.layout.resize();};if(win instanceof Window){win.center();win.show();}else{win.layout.layout(true);}return win; }
    buildUI(thisObj);
})(this);
